site_name: testing
site_url: https://docutest.github.io/mkdocstest1/
theme:
  name: material
  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format